apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hackqc2024
images:
- name: ghcr.io/clubcedille/hackqc2024
  newTag: commit-54ffde89f8d220f9b397869ca80f7e65e52ae4f2

resources:
- namespace.yaml
- pv.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
