apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hackqc2024
images:
- name: ghcr.io/clubcedille/hackqc2024
  newTag: commit-f239202baeeb33a3bc8840426361728a49c5f3c0

resources:
- namespace.yaml
- pv.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
