apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hackqc2024
images:
- name: ghcr.io/clubcedille/hackqc2024
  newTag: commit-5ed60d99989380425fee516d6bb28ff9af7e3500

resources:
- namespace.yaml
- pv.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
