apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hackqc2024
images:
- name: ghcr.io/clubcedille/hackqc2024
  newTag: commit-8842f4e48ee2869034ce95ba17f583f45a98a76a

resources:
- namespace.yaml
- pv.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
