apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hackqc2024
images:
- name: ghcr.io/clubcedille/hackqc2024
  newTag: commit-9d0733136b468ab47d5e0e45bcfce8599b2f76cc

resources:
- namespace.yaml
- pv.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
